### ISSUE TITLE
Configurations not getting saved after making changes

### ISSUE THREAD

**Issue by anandsarath** [Nauplius/BLOBCache#1]
Hi 

I am getting the following error after making changes in the BLOB cache configuration
![capture](https://cloud.githubusercontent.com/assets/26873829/24612441/e4ff4582-18a2-11e7-9ca3-7ecf05e29c84.PNG)

**Comment by tseward** [comment]
Can you monitor your ULS logs while attempting to save the settings to see if something is throwing an error?

**Comment by anandsarath** [comment]
Hi 
 I got the following error, I am using SharePoint 2013 Foundation Edition.


1. WebConfigModification: Error setting web.config attribute value. Path - configuration/SharePoint/BlobCache Attribute name - enabled Attribute value - false. Path NOT FOUND in web.config file C:****\*********\web.config
2. WebConfigModification: Applying WebConfigModifications FAILED for web.config file C:****\*********\web.config for web app SharePoint - XXX. 
Exception message - Failed to apply a web.config modification to file 'C:****\*********\web.config'.  The specified node "configuration/SharePoint/BlobCache" was not found in the web.config file.
3. WebConfigModification: Changes not applied to web application

**Comment by tseward** [comment]
This is going to be an issue with the farm configuration. My best bet would be to stop the Foundation Web service on the server showing the error and starting it again. What this will do is remove the IIS Sites and App Pools supporting the Web Applications, then re-deploy them. Anything custom you may have done to the web.config or IIS bindings will be lost during this process, so proceed with caution.

**Comment by anandsarath** [comment]
Hi 
I tired restating the "Microsoft SharePoint Foundation Web Application "  but still I am getting the same error. Guess BLOB caching is not supported in SharePoint 2013 Foundation Edition.

**Comment by tseward** [comment]
Correct, if you're running SharePoint Foundation, then BLOBCache isn't available as it is a Publishing feature. That said, SharePoint Server has the Service Instance named 'Microsoft.SharePoint Foundation Web Application'.
