### ISSUE TITLE
Max-Age value 0 not accepted

### ISSUE THREAD

**Issue by LouFarho** [Nauplius/BLOBCache#3]
I wish to set the max-age to zero but it is throwing an exception.
I base this decision on this article. If you feel this is a flawed analysis, i am open to your feedback.
[https://sharepointinterface.com/2012/03/12/do-you-know-whats-going-to-happen-when-you-enable-the-sharepoint-blob-cache/](url)

`Application error when access /_admin/SharePoint.BLOBCache/BlobCacheSettings.aspx, Error=Input string was not in a correct format.   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)     at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)     at System.Convert.ToInt64(String value)     at Nauplius.SharePoint.BlobCache.Layouts.Nauplius.SharePoint.BlobCache.BlobCacheSettings.MaxCacheAge(String maxAge)     at Nauplius.SharePoint.BlobCache.Layouts.Nauplius.SharePoint.BlobCache.BlobCacheSettings.BtnSave_OnSaveEx(Object sender, EventArgs e)     at System.Web.UI.WebControls.Button.OnClick(EventArgs e)     at System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument)     at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

**Comment by tseward** [comment]
There's no reason you shouldn't be able to set that to zero. I see why this feature is throwing the error -- it's due to removing a function removing leading zeros :(. I'll get this fixed. Thanks for finding it!

**Comment by tseward** [comment]
@LouFarho I've pushed updates for SharePoint 2016/2019. Which version of SharePoint are you using? I don't have any 2010/2013 farms on hand right now.

**Comment by LouFarho** [comment]
Thanks @tseward! I am using this on a 2019 Farm.
I will be able to test this today.

Sorry, I was out of the office yesterday.
